// Code generated by gen_tf_models. DO NOT EDIT.
package event_criticalities

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type EventCriticalitiesTF struct {
	general_objects.AuditModelTF
	Name     types.String                 `tfsdk:"name"`
	ReadOnly types.Bool                   `tfsdk:"read_only"`
	Tags     []general_objects.KeyValueTF `tfsdk:"tags"`
}

func (x *EventCriticalities) ToTF() any {
	return general_objects.ReflectToTF[EventCriticalitiesTF](x)
}

func (tf *EventCriticalitiesTF) ToAPI() any {
	return general_objects.ReflectFromTF[EventCriticalities](tf)
}
