// Code generated by gen_tf_models. DO NOT EDIT.
package activity_states

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type ActivityStateTF struct {
	general_objects.AuditModelTF
	Name     types.String `tfsdk:"name"`
	ReadOnly types.Bool   `tfsdk:"read_only"`
}

func (x *ActivityState) ToTF() any {
	return general_objects.ReflectToTF[ActivityStateTF](x)
}

func (tf *ActivityStateTF) ToAPI() any {
	return general_objects.ReflectFromTF[ActivityState](tf)
}
