// Code generated by gen_tf_models. DO NOT EDIT.
package resources

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type ResourceThresholdTF struct {
	Kind                 types.String  `tfsdk:"kind"`
	Name                 types.String  `tfsdk:"name"`
	ViolationWhenReached types.Bool    `tfsdk:"violation_when_reached"`
	Value                types.Float64 `tfsdk:"value"`
}

type ResourceTF struct {
	general_objects.AuditModelTF
	AssetId      types.String                 `tfsdk:"asset_id"`
	UnitId       types.String                 `tfsdk:"unit_id"`
	MetricId     types.String                 `tfsdk:"metric_id"`
	Name         types.String                 `tfsdk:"name"`
	Description  types.String                 `tfsdk:"description"`
	DefaultLevel types.Float64                `tfsdk:"default_level"`
	LowerLimit   types.Float64                `tfsdk:"lower_limit"`
	UpperLimit   types.Float64                `tfsdk:"upper_limit"`
	Thresholds   []ResourceThresholdTF        `tfsdk:"thresholds"`
	Tags         []general_objects.KeyValueTF `tfsdk:"tags"`
}

func (x *Resource) ToTF() any {
	return &ResourceTF{
		AuditModelTF: general_objects.AuditModelToTF(&x.AuditModel),
		AssetId:      helper.TFStringValue(x.AssetId),
		UnitId:       helper.TFStringValue(x.UnitId),
		MetricId:     helper.TFStringPtrValue(x.MetricId),
		Name:         helper.TFStringValue(x.Name),
		Description:  helper.TFStringPtrValue(x.Description),
		DefaultLevel: helper.TFFloat64Value(x.DefaultLevel),
		LowerLimit:   helper.TFFloat64PtrValue(x.LowerLimit),
		UpperLimit:   helper.TFFloat64PtrValue(x.UpperLimit),
		Thresholds:   resourceThresholdSliceToTF(x.Thresholds),
		Tags:         general_objects.KeyValuesToTF(x.Tags),
	}
}

func (tf *ResourceTF) ToAPI() any {
	return &Resource{
		AuditModel:   general_objects.AuditModelFromTF(tf.AuditModelTF),
		AssetId:      helper.FromTFString(tf.AssetId),
		UnitId:       helper.FromTFString(tf.UnitId),
		MetricId:     helper.FromTFStringPtr(tf.MetricId),
		Name:         helper.FromTFString(tf.Name),
		Description:  helper.FromTFStringPtr(tf.Description),
		DefaultLevel: helper.FromTFFloat64(tf.DefaultLevel),
		LowerLimit:   helper.FromTFFloat64Ptr(tf.LowerLimit),
		UpperLimit:   helper.FromTFFloat64Ptr(tf.UpperLimit),
		Thresholds:   resourceThresholdSliceFromTF(tf.Thresholds),
		Tags:         general_objects.KeyValuesFromTF(tf.Tags),
	}
}

func resourceThresholdToTF(x *ResourceThreshold) *ResourceThresholdTF {
	if x == nil {
		return nil
	}
	return general_objects.ReflectToTF[ResourceThresholdTF](x)
}

func resourceThresholdFromTF(tf *ResourceThresholdTF) *ResourceThreshold {
	if tf == nil {
		return nil
	}
	return general_objects.ReflectFromTF[ResourceThreshold](tf)
}

func resourceThresholdValueFromTF(tf *ResourceThresholdTF) ResourceThreshold {
	if v := resourceThresholdFromTF(tf); v != nil {
		return *v
	}
	return ResourceThreshold{}
}

func resourceThresholdSliceToTF(xs []ResourceThreshold) []ResourceThresholdTF {
	result := make([]ResourceThresholdTF, len(xs))
	for i := range xs {
		result[i] = *general_objects.ReflectToTF[ResourceThresholdTF](&xs[i])
	}
	return result
}

func resourceThresholdSliceFromTF(tfs []ResourceThresholdTF) []ResourceThreshold {
	result := make([]ResourceThreshold, len(tfs))
	for i := range tfs {
		result[i] = *general_objects.ReflectFromTF[ResourceThreshold](&tfs[i])
	}
	return result
}
