// Code generated by gen_tf_models. DO NOT EDIT.
package request_states

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type RequestStateTF struct {
	general_objects.AuditModelTF
	Name types.String `tfsdk:"name"`
}

func (x *RequestState) ToTF() any {
	return general_objects.ReflectToTF[RequestStateTF](x)
}

func (tf *RequestStateTF) ToAPI() any {
	return general_objects.ReflectFromTF[RequestState](tf)
}
