// Code generated by gen_tf_models. DO NOT EDIT.
package sensors

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type HalfApertureAngleTF struct {
	Degrees types.Float64 `tfsdk:"degrees"`
}

type Vector3DTF struct {
	X types.Float64 `tfsdk:"x"`
	Y types.Float64 `tfsdk:"y"`
	Z types.Float64 `tfsdk:"z"`
}

type ApertureShapeTF struct {
	Type                        types.String         `tfsdk:"type"`
	ApertureCenter              *Vector3DTF          `tfsdk:"aperture_center"`
	HalfApertureAngle           *HalfApertureAngleTF `tfsdk:"half_aperture_angle"`
	FirstAxisVector             *Vector3DTF          `tfsdk:"first_axis_vector"`
	FirstAxisHalfApertureAngle  *HalfApertureAngleTF `tfsdk:"first_axis_half_aperture_angle"`
	SecondAxisVector            *Vector3DTF          `tfsdk:"second_axis_vector"`
	SecondAxisHalfApertureAngle *HalfApertureAngleTF `tfsdk:"second_axis_half_aperture_angle"`
}

type SensorTF struct {
	general_objects.AuditModelTF
	SatelliteID   types.String                 `tfsdk:"satellite_id"`
	Name          types.String                 `tfsdk:"name"`
	ApertureShape *ApertureShapeTF             `tfsdk:"aperture_shape"`
	Tags          []general_objects.KeyValueTF `tfsdk:"tags"`
}

func (x *Sensor) ToTF() any {
	return &SensorTF{
		AuditModelTF:  general_objects.AuditModelToTF(&x.AuditModel),
		SatelliteID:   helper.TFStringValue(x.SatelliteID),
		Name:          helper.TFStringValue(x.Name),
		ApertureShape: apertureShapeToTF(x.ApertureShape),
		Tags:          general_objects.KeyValuesToTF(x.Tags),
	}
}

func (tf *SensorTF) ToAPI() any {
	return &Sensor{
		AuditModel:    general_objects.AuditModelFromTF(tf.AuditModelTF),
		SatelliteID:   helper.FromTFString(tf.SatelliteID),
		Name:          helper.FromTFString(tf.Name),
		ApertureShape: apertureShapeFromTF(tf.ApertureShape),
		Tags:          general_objects.KeyValuesFromTF(tf.Tags),
	}
}

func halfApertureAngleToTF(x *HalfApertureAngle) *HalfApertureAngleTF {
	if x == nil {
		return nil
	}
	return general_objects.ReflectToTF[HalfApertureAngleTF](x)
}

func halfApertureAngleFromTF(tf *HalfApertureAngleTF) *HalfApertureAngle {
	if tf == nil {
		return nil
	}
	return general_objects.ReflectFromTF[HalfApertureAngle](tf)
}

func halfApertureAngleValueFromTF(tf *HalfApertureAngleTF) HalfApertureAngle {
	if v := halfApertureAngleFromTF(tf); v != nil {
		return *v
	}
	return HalfApertureAngle{}
}

func halfApertureAngleSliceToTF(xs []HalfApertureAngle) []HalfApertureAngleTF {
	result := make([]HalfApertureAngleTF, len(xs))
	for i := range xs {
		result[i] = *general_objects.ReflectToTF[HalfApertureAngleTF](&xs[i])
	}
	return result
}

func halfApertureAngleSliceFromTF(tfs []HalfApertureAngleTF) []HalfApertureAngle {
	result := make([]HalfApertureAngle, len(tfs))
	for i := range tfs {
		result[i] = *general_objects.ReflectFromTF[HalfApertureAngle](&tfs[i])
	}
	return result
}

func vector3DToTF(x *Vector3D) *Vector3DTF {
	if x == nil {
		return nil
	}
	return general_objects.ReflectToTF[Vector3DTF](x)
}

func vector3DFromTF(tf *Vector3DTF) *Vector3D {
	if tf == nil {
		return nil
	}
	return general_objects.ReflectFromTF[Vector3D](tf)
}

func vector3DValueFromTF(tf *Vector3DTF) Vector3D {
	if v := vector3DFromTF(tf); v != nil {
		return *v
	}
	return Vector3D{}
}

func vector3DSliceToTF(xs []Vector3D) []Vector3DTF {
	result := make([]Vector3DTF, len(xs))
	for i := range xs {
		result[i] = *general_objects.ReflectToTF[Vector3DTF](&xs[i])
	}
	return result
}

func vector3DSliceFromTF(tfs []Vector3DTF) []Vector3D {
	result := make([]Vector3D, len(tfs))
	for i := range tfs {
		result[i] = *general_objects.ReflectFromTF[Vector3D](&tfs[i])
	}
	return result
}

func apertureShapeToTF(x *ApertureShape) *ApertureShapeTF {
	if x == nil {
		return nil
	}
	return &ApertureShapeTF{
		Type:                        helper.TFStringValue(x.Type),
		ApertureCenter:              vector3DToTF(x.ApertureCenter),
		HalfApertureAngle:           halfApertureAngleToTF(x.HalfApertureAngle),
		FirstAxisVector:             vector3DToTF(x.FirstAxisVector),
		FirstAxisHalfApertureAngle:  halfApertureAngleToTF(x.FirstAxisHalfApertureAngle),
		SecondAxisVector:            vector3DToTF(x.SecondAxisVector),
		SecondAxisHalfApertureAngle: halfApertureAngleToTF(x.SecondAxisHalfApertureAngle),
	}
}

func apertureShapeFromTF(tf *ApertureShapeTF) *ApertureShape {
	if tf == nil {
		return nil
	}
	return &ApertureShape{
		Type:                        helper.FromTFString(tf.Type),
		ApertureCenter:              vector3DFromTF(tf.ApertureCenter),
		HalfApertureAngle:           halfApertureAngleFromTF(tf.HalfApertureAngle),
		FirstAxisVector:             vector3DFromTF(tf.FirstAxisVector),
		FirstAxisHalfApertureAngle:  halfApertureAngleFromTF(tf.FirstAxisHalfApertureAngle),
		SecondAxisVector:            vector3DFromTF(tf.SecondAxisVector),
		SecondAxisHalfApertureAngle: halfApertureAngleFromTF(tf.SecondAxisHalfApertureAngle),
	}
}

func apertureShapeValueFromTF(tf *ApertureShapeTF) ApertureShape {
	if v := apertureShapeFromTF(tf); v != nil {
		return *v
	}
	return ApertureShape{}
}

func apertureShapeSliceToTF(xs []ApertureShape) []ApertureShapeTF {
	result := make([]ApertureShapeTF, len(xs))
	for i := range xs {
		result[i] = *apertureShapeToTF(&xs[i])
	}
	return result
}

func apertureShapeSliceFromTF(tfs []ApertureShapeTF) []ApertureShape {
	result := make([]ApertureShape, len(tfs))
	for i := range tfs {
		result[i] = *apertureShapeFromTF(&tfs[i])
	}
	return result
}
