// Code generated by gen_tf_models. DO NOT EDIT.
package generic_plugins

import (
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type GenericPluginTF struct {
	general_objects.AuditModelTF
	Name           types.String `tfsdk:"name"`
	Description    types.String `tfsdk:"description"`
	Type           types.String `tfsdk:"type"`
	Language       types.String `tfsdk:"language"`
	SourceCodeLink types.Object `tfsdk:"source_code_link"`
	Status         types.String `tfsdk:"status"`
	FilePath       types.String `tfsdk:"source_code_path"`
	FileSha        types.String `tfsdk:"source_code_sha"`
}

func (x *GenericPlugin) ToTF() any {
	return &GenericPluginTF{
		AuditModelTF:   general_objects.AuditModelToTF(&x.AuditModel),
		Name:           types.StringValue(x.Name),
		Description:    types.StringPointerValue(x.Description),
		Type:           types.StringValue(x.Type),
		Language:       types.StringValue(x.Language),
		SourceCodeLink: sourceCodeLinkToObject(&x.SourceCodeLink),
		Status:         types.StringValue(x.Status),
		FilePath:       types.StringValue(x.FilePath),
		FileSha:        types.StringValue(x.FileSha),
	}
}

func (tf *GenericPluginTF) ToAPI() any {
	return &GenericPlugin{
		AuditModel:     general_objects.AuditModelFromTF(tf.AuditModelTF),
		Name:           tf.Name.ValueString(),
		Description:    tf.Description.ValueStringPointer(),
		Type:           tf.Type.ValueString(),
		Language:       tf.Language.ValueString(),
		SourceCodeLink: sourceCodeLinkFromObject(tf.SourceCodeLink),
		Status:         tf.Status.ValueString(),
		FilePath:       tf.FilePath.ValueString(),
		FileSha:        tf.FileSha.ValueString(),
	}
}

var sourceCodeLinkAttrTypes = map[string]attr.Type{
	"expiration_time": types.StringType,
	"source_code_id":  types.StringType,
	"url":             types.StringType,
}

func sourceCodeLinkToObject(x *SourceCodeLink) types.Object {
	if x == nil {
		return types.ObjectNull(sourceCodeLinkAttrTypes)
	}
	return types.ObjectValueMust(sourceCodeLinkAttrTypes, map[string]attr.Value{
		"expiration_time": types.StringValue(x.ExpirationTime),
		"source_code_id":  types.StringValue(x.SourceCodeId),
		"url":             types.StringValue(x.Url),
	})
}

func sourceCodeLinkFromObject(obj types.Object) SourceCodeLink {
	if obj.IsNull() || obj.IsUnknown() {
		return SourceCodeLink{}
	}
	attrs := obj.Attributes()
	return SourceCodeLink{
		ExpirationTime: attrs["expiration_time"].(types.String).ValueString(),
		SourceCodeId:   attrs["source_code_id"].(types.String).ValueString(),
		Url:            attrs["url"].(types.String).ValueString(),
	}
}
