// Code generated by gen_tf_models. DO NOT EDIT.
package teams

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type TeamTF struct {
	general_objects.AuditModelTF
	Name      types.String                 `tfsdk:"name"`
	PolicyIds []types.String               `tfsdk:"policy_ids"`
	Members   []types.String               `tfsdk:"members"`
	Tags      []general_objects.KeyValueTF `tfsdk:"tags"`
}

func (x *Team) ToTF() any {
	return general_objects.ReflectToTF[TeamTF](x)
}

func (tf *TeamTF) ToAPI() any {
	return general_objects.ReflectFromTF[Team](tf)
}
