// Code generated by gen_tf_models. DO NOT EDIT.
package access_policies

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type StatementTF struct {
	Name    types.String   `tfsdk:"name"`
	Actions []types.String `tfsdk:"actions"`
}

type AccessPolicyTF struct {
	general_objects.AuditModelTF
	Name        types.String                 `tfsdk:"name"`
	Description types.String                 `tfsdk:"description"`
	ReadOnly    types.Bool                   `tfsdk:"read_only"`
	Statements  []StatementTF                `tfsdk:"statements"`
	Tags        []general_objects.KeyValueTF `tfsdk:"tags"`
}

func (x *AccessPolicy) ToTF() any {
	return &AccessPolicyTF{
		AuditModelTF: general_objects.AuditModelToTF(&x.AuditModel),
		Name:         types.StringValue(x.Name),
		Description:  helper.TFStringPtrValue(x.Description),
		ReadOnly:     types.BoolValue(x.ReadOnly),
		Statements:   statementSliceToTF(x.Statements),
		Tags:         general_objects.KeyValuesToTF(x.Tags),
	}
}

func (tf *AccessPolicyTF) ToAPI() any {
	return &AccessPolicy{
		AuditModel:  general_objects.AuditModelFromTF(tf.AuditModelTF),
		Name:        helper.FromTFString(tf.Name),
		Description: helper.FromTFStringPtr(tf.Description),
		ReadOnly:    helper.FromTFBool(tf.ReadOnly),
		Statements:  statementSliceFromTF(tf.Statements),
		Tags:        general_objects.KeyValuesFromTF(tf.Tags),
	}
}

func statementToTF(x *Statement) *StatementTF {
	if x == nil {
		return nil
	}
	return general_objects.ReflectToTF[StatementTF](x)
}

func statementFromTF(tf *StatementTF) *Statement {
	if tf == nil {
		return nil
	}
	return general_objects.ReflectFromTF[Statement](tf)
}

func statementValueFromTF(tf *StatementTF) Statement {
	if v := statementFromTF(tf); v != nil {
		return *v
	}
	return Statement{}
}

func statementSliceToTF(xs []Statement) []StatementTF {
	result := make([]StatementTF, len(xs))
	for i := range xs {
		result[i] = *general_objects.ReflectToTF[StatementTF](&xs[i])
	}
	return result
}

func statementSliceFromTF(tfs []StatementTF) []Statement {
	result := make([]Statement, len(tfs))
	for i := range tfs {
		result[i] = *general_objects.ReflectFromTF[Statement](&tfs[i])
	}
	return result
}
