package services

import (
	"github.com/leanspace/terraform-provider-leanspace/provider"
	"github.com/leanspace/terraform-provider-leanspace/services/activities/activity_definitions"
	"github.com/leanspace/terraform-provider-leanspace/services/activities/activity_states"
	"github.com/leanspace/terraform-provider-leanspace/services/activities/resource_functions"
	"github.com/leanspace/terraform-provider-leanspace/services/asset/nodes"
	"github.com/leanspace/terraform-provider-leanspace/services/asset/properties"
	"github.com/leanspace/terraform-provider-leanspace/services/asset/units"
	"github.com/leanspace/terraform-provider-leanspace/services/commands/command_definitions"
	"github.com/leanspace/terraform-provider-leanspace/services/commands/command_queues"
	"github.com/leanspace/terraform-provider-leanspace/services/commands/command_sequence_states"
	"github.com/leanspace/terraform-provider-leanspace/services/commands/command_states"
	"github.com/leanspace/terraform-provider-leanspace/services/commands/release_queues"
	"github.com/leanspace/terraform-provider-leanspace/services/dashboard/dashboards"
	"github.com/leanspace/terraform-provider-leanspace/services/dashboard/widgets"
	"github.com/leanspace/terraform-provider-leanspace/services/events/event_criticalities"
	"github.com/leanspace/terraform-provider-leanspace/services/events/event_definitions"
	"github.com/leanspace/terraform-provider-leanspace/services/leaf_space_integration/connections"
	"github.com/leanspace/terraform-provider-leanspace/services/leaf_space_integration/contact_reservation_status_mappings"
	groundstation_links "github.com/leanspace/terraform-provider-leanspace/services/leaf_space_integration/link/ground_station"
	satellite_links "github.com/leanspace/terraform-provider-leanspace/services/leaf_space_integration/link/satellite"
	"github.com/leanspace/terraform-provider-leanspace/services/metrics/metrics"
	"github.com/leanspace/terraform-provider-leanspace/services/monitors/action_templates"
	"github.com/leanspace/terraform-provider-leanspace/services/monitors/monitors"
	"github.com/leanspace/terraform-provider-leanspace/services/orbits/areas_of_interest"
	"github.com/leanspace/terraform-provider-leanspace/services/orbits/orbits"
	"github.com/leanspace/terraform-provider-leanspace/services/orbits/sensors"
	"github.com/leanspace/terraform-provider-leanspace/services/pass/contact_states"
	"github.com/leanspace/terraform-provider-leanspace/services/pass/pass_delay_configuration"
	"github.com/leanspace/terraform-provider-leanspace/services/pass/pass_states"
	"github.com/leanspace/terraform-provider-leanspace/services/plans/plan_states"
	"github.com/leanspace/terraform-provider-leanspace/services/plans/plan_templates"
	"github.com/leanspace/terraform-provider-leanspace/services/plugins/generic_plugins"
	"github.com/leanspace/terraform-provider-leanspace/services/plugins/plugins"
	"github.com/leanspace/terraform-provider-leanspace/services/records/record_templates"
	"github.com/leanspace/terraform-provider-leanspace/services/requests/feasibility_constraint_definitions"
	"github.com/leanspace/terraform-provider-leanspace/services/requests/request_definitions"
	"github.com/leanspace/terraform-provider-leanspace/services/requests/request_states"
	"github.com/leanspace/terraform-provider-leanspace/services/resources/passive_resource_functions"
	"github.com/leanspace/terraform-provider-leanspace/services/resources/resources"
	"github.com/leanspace/terraform-provider-leanspace/services/routes/processors"
	"github.com/leanspace/terraform-provider-leanspace/services/routes/routes"
	"github.com/leanspace/terraform-provider-leanspace/services/streams/stream_queues"
	"github.com/leanspace/terraform-provider-leanspace/services/streams/streams"
	"github.com/leanspace/terraform-provider-leanspace/services/teams/access_policies"
	"github.com/leanspace/terraform-provider-leanspace/services/teams/members"
	"github.com/leanspace/terraform-provider-leanspace/services/teams/service_accounts"
	"github.com/leanspace/terraform-provider-leanspace/services/teams/teams"
)

func register[T any, PT provider.ParseableModel[T]](dt *provider.DataSourceType[T, PT]) {
	provider.RegisterResource(provider.NewGenericResource(dt))
	provider.RegisterDataSource(provider.NewGenericDataSource(dt))
}

func RegisterDataTypes() {
	register(&access_policies.AccessPolicyDataType)
	register(&action_templates.ActionTemplateDataType)
	register(&activity_definitions.ActivityDefinitionDataType)
	register(&resource_functions.ResourceFunctionDataType)
	register(&command_definitions.CommandDataType)
	register(&command_queues.CommandQueueDataType)
	register(&release_queues.ReleaseQueueDataType)
	register(&command_sequence_states.CommandSequenceStateDataType)
	register(&command_states.CommandStateDataType)
	register(&dashboards.DashboardDataType)
	register(&members.MemberDataType)
	register(&metrics.MetricDataType)
	register(&monitors.MonitorDataType)
	register(&nodes.NodeDataType)
	register(&generic_plugins.GenericPluginDataType)
	register(&plugins.PluginDataType)
	register(&properties.PropertyDataType)
	register(&record_templates.RecordTemplateDataType)
	register(&service_accounts.ServiceAccountDataType)
	register(&streams.StreamDataType)
	register(&stream_queues.StreamQueueDataType)
	register(&teams.TeamDataType)
	register(&units.UnitDataType)
	register(&widgets.WidgetDataType)
	register(&plan_states.PlanStateDataType)
	register(&plan_templates.PlanTemplateDataType)
	register(&pass_states.PassStateDataType)
	register(&contact_states.ContactStateDataType)
	register(&pass_delay_configuration.PassDelayConfigurationType)
	register(&activity_states.ActivityStateDataType)
	register(&routes.RouteDataType)
	register(&processors.ProcessorDataType)
	register(&orbits.OrbitDataType)
	register(&connections.LeafSpaceConnectionDataType)
	register(&groundstation_links.LeafSpaceGroundStationLinkDataType)
	register(&satellite_links.LeafSpaceSatellitesLinkDataType)
	register(&contact_reservation_status_mappings.LeafSpaceContactReservationStatusMappingDataType)
	register(&resources.ResourceDataType)
	register(&passive_resource_functions.PassiveResourceFunctionDataType)
	register(&event_definitions.EventsDefinitionDataType)
	register(&event_criticalities.EventCriticalitiesDataType)
	register(&feasibility_constraint_definitions.FeasibilityConstraintDefinitionDataType)
	register(&request_definitions.RequestDefinitionDataType)
	register(&request_states.RequestStateDataType)
	register(&areas_of_interest.AreaOfInterestDataType)
	register(&sensors.SensorDataType)
}
