// Code generated by gen_tf_models. DO NOT EDIT.
package pass_states

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type PassStateTF struct {
	general_objects.AuditModelTF
	Name     types.String `tfsdk:"name"`
	ReadOnly types.Bool   `tfsdk:"read_only"`
}

func (x *PassState) ToTF() any {
	return general_objects.ReflectToTF[PassStateTF](x)
}

func (tf *PassStateTF) ToAPI() any {
	return general_objects.ReflectFromTF[PassState](tf)
}
