// Code generated by gen_tf_models. DO NOT EDIT.
package release_queues

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type ReleaseQueueTF struct {
	general_objects.AuditModelTF
	AssetId                                   types.String                 `tfsdk:"asset_id"`
	Name                                      types.String                 `tfsdk:"name"`
	Description                               types.String                 `tfsdk:"description"`
	CommandTransformerPluginId                types.String                 `tfsdk:"command_transformer_plugin_id"`
	CommandTransformationStrategy             types.String                 `tfsdk:"command_transformation_strategy"`
	CommandTransformerPluginConfigurationData types.String                 `tfsdk:"command_transformer_plugin_configuration_data"`
	GlobalTransmissionMetadata                []general_objects.KeyValueTF `tfsdk:"global_transmission_metadata"`
	LogicalLock                               types.Bool                   `tfsdk:"logical_lock"`
	Tags                                      []general_objects.KeyValueTF `tfsdk:"tags"`
}

func (x *ReleaseQueue) ToTF() any {
	return general_objects.ReflectToTF[ReleaseQueueTF](x)
}

func (tf *ReleaseQueueTF) ToAPI() any {
	return general_objects.ReflectFromTF[ReleaseQueue](tf)
}
