// Code generated by gen_tf_models. DO NOT EDIT.
package resource_functions

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type ResourceFunctionFormulaTF struct {
	Type      types.String  `tfsdk:"type"`
	Amplitude types.Float64 `tfsdk:"amplitude"`
	Constant  types.Float64 `tfsdk:"constant"`
	Rate      types.Float64 `tfsdk:"rate"`
	TimeUnit  types.String  `tfsdk:"time_unit"`
}

type ResourceFunctionTF struct {
	general_objects.AuditModelTF
	ActivityDefinitionId types.String               `tfsdk:"activity_definition_id"`
	ResourceId           types.String               `tfsdk:"resource_id"`
	Name                 types.String               `tfsdk:"name"`
	Formula              *ResourceFunctionFormulaTF `tfsdk:"formula"`
}

func (x *ResourceFunction) ToTF() any {
	return &ResourceFunctionTF{
		AuditModelTF:         general_objects.AuditModelToTF(&x.AuditModel),
		ActivityDefinitionId: helper.TFStringValue(x.ActivityDefinitionId),
		ResourceId:           helper.TFStringValue(x.ResourceId),
		Name:                 helper.TFStringValue(x.Name),
		Formula:              resourceFunctionFormulaToTF(x.Formula),
	}
}

func (tf *ResourceFunctionTF) ToAPI() any {
	return &ResourceFunction{
		AuditModel:           general_objects.AuditModelFromTF(tf.AuditModelTF),
		ActivityDefinitionId: helper.FromTFString(tf.ActivityDefinitionId),
		ResourceId:           helper.FromTFString(tf.ResourceId),
		Name:                 helper.FromTFString(tf.Name),
		Formula:              resourceFunctionFormulaFromTF(tf.Formula),
	}
}

func resourceFunctionFormulaToTF(x *ResourceFunctionFormula) *ResourceFunctionFormulaTF {
	if x == nil {
		return nil
	}
	return general_objects.ReflectToTF[ResourceFunctionFormulaTF](x)
}

func resourceFunctionFormulaFromTF(tf *ResourceFunctionFormulaTF) *ResourceFunctionFormula {
	if tf == nil {
		return nil
	}
	return general_objects.ReflectFromTF[ResourceFunctionFormula](tf)
}

func resourceFunctionFormulaValueFromTF(tf *ResourceFunctionFormulaTF) ResourceFunctionFormula {
	if v := resourceFunctionFormulaFromTF(tf); v != nil {
		return *v
	}
	return ResourceFunctionFormula{}
}

func resourceFunctionFormulaSliceToTF(xs []ResourceFunctionFormula) []ResourceFunctionFormulaTF {
	result := make([]ResourceFunctionFormulaTF, len(xs))
	for i := range xs {
		result[i] = *general_objects.ReflectToTF[ResourceFunctionFormulaTF](&xs[i])
	}
	return result
}

func resourceFunctionFormulaSliceFromTF(tfs []ResourceFunctionFormulaTF) []ResourceFunctionFormula {
	result := make([]ResourceFunctionFormula, len(tfs))
	for i := range tfs {
		result[i] = *general_objects.ReflectFromTF[ResourceFunctionFormula](&tfs[i])
	}
	return result
}
