// Code generated by gen_tf_models. DO NOT EDIT.
package service_accounts

import (
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type ServiceAccountTF struct {
	general_objects.AuditModelTF
	Name        types.String                 `tfsdk:"name"`
	PolicyIds   []types.String               `tfsdk:"policy_ids"`
	Credentials types.Object                 `tfsdk:"credentials"`
	Tags        []general_objects.KeyValueTF `tfsdk:"tags"`
}

func (x *ServiceAccount) ToTF() any {
	return &ServiceAccountTF{
		AuditModelTF: general_objects.AuditModelToTF(&x.AuditModel),
		Name:         types.StringValue(x.Name),
		PolicyIds:    helper.TFStringsValue(x.PolicyIds),
		Credentials:  credentialsToObject(&x.Credentials),
		Tags:         general_objects.KeyValuesToTF(x.Tags),
	}
}

func (tf *ServiceAccountTF) ToAPI() any {
	return &ServiceAccount{
		AuditModel:  general_objects.AuditModelFromTF(tf.AuditModelTF),
		Name:        tf.Name.ValueString(),
		PolicyIds:   helper.FromTFStrings(tf.PolicyIds),
		Credentials: credentialsFromObject(tf.Credentials),
		Tags:        general_objects.KeyValuesFromTF(tf.Tags),
	}
}

var credentialsAttrTypes = map[string]attr.Type{
	"client_id":     types.StringType,
	"client_secret": types.StringType,
}

func credentialsToObject(x *Credentials) types.Object {
	if x == nil {
		return types.ObjectNull(credentialsAttrTypes)
	}
	return types.ObjectValueMust(credentialsAttrTypes, map[string]attr.Value{
		"client_id":     types.StringValue(x.ClientId),
		"client_secret": types.StringValue(x.ClientSecret),
	})
}

func credentialsFromObject(obj types.Object) Credentials {
	if obj.IsNull() || obj.IsUnknown() {
		return Credentials{}
	}
	attrs := obj.Attributes()
	return Credentials{
		ClientId:     attrs["client_id"].(types.String).ValueString(),
		ClientSecret: attrs["client_secret"].(types.String).ValueString(),
	}
}
