// Code generated by gen_tf_models. DO NOT EDIT.
package routes

import (
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type DefinitionTF struct {
	Configuration    types.String `tfsdk:"configuration"`
	LogLevel         types.String `tfsdk:"log_level"`
	Valid            types.Bool   `tfsdk:"valid"`
	ServiceAccountId types.String `tfsdk:"service_account_id"`
	Errors           types.List   `tfsdk:"errors"`
}

type RouteTF struct {
	general_objects.AuditModelTF
	Name           types.String                 `tfsdk:"name"`
	Description    types.String                 `tfsdk:"description"`
	Tags           []general_objects.KeyValueTF `tfsdk:"tags"`
	Definition     *DefinitionTF                `tfsdk:"definition"`
	RouteInstances types.List                   `tfsdk:"route_instances"`
	ProcessorIds   []types.String               `tfsdk:"processor_ids"`
}

func (x *Route) ToTF() any {
	return &RouteTF{
		AuditModelTF:   general_objects.AuditModelToTF(&x.AuditModel),
		Name:           types.StringValue(x.Name),
		Description:    types.StringPointerValue(x.Description),
		Tags:           general_objects.KeyValuesToTF(x.Tags),
		Definition:     definitionToTF(&x.Definition),
		RouteInstances: routeInstanceToList(x.RouteInstances),
		ProcessorIds:   helper.TFStringsValue(x.ProcessorIds),
	}
}

func (tf *RouteTF) ToAPI() any {
	return &Route{
		AuditModel:     general_objects.AuditModelFromTF(tf.AuditModelTF),
		Name:           tf.Name.ValueString(),
		Description:    tf.Description.ValueStringPointer(),
		Tags:           general_objects.KeyValuesFromTF(tf.Tags),
		Definition:     definitionValueFromTF(tf.Definition),
		RouteInstances: routeInstanceFromList(tf.RouteInstances),
		ProcessorIds:   helper.FromTFStrings(tf.ProcessorIds),
	}
}

func definitionToTF(x *Definition) *DefinitionTF {
	if x == nil {
		return nil
	}
	return &DefinitionTF{
		Configuration:    types.StringValue(x.Configuration),
		LogLevel:         types.StringValue(x.LogLevel),
		Valid:            types.BoolValue(x.Valid),
		ServiceAccountId: types.StringPointerValue(x.ServiceAccountId),
		Errors:           errorToList(x.Errors),
	}
}

func definitionFromTF(tf *DefinitionTF) *Definition {
	if tf == nil {
		return nil
	}
	return &Definition{
		Configuration:    tf.Configuration.ValueString(),
		LogLevel:         tf.LogLevel.ValueString(),
		Valid:            tf.Valid.ValueBool(),
		ServiceAccountId: tf.ServiceAccountId.ValueStringPointer(),
		Errors:           errorFromList(tf.Errors),
	}
}

func definitionValueFromTF(tf *DefinitionTF) Definition {
	if v := definitionFromTF(tf); v != nil {
		return *v
	}
	return Definition{}
}

func definitionSliceToTF(xs []Definition) []DefinitionTF {
	result := make([]DefinitionTF, len(xs))
	for i := range xs {
		result[i] = *definitionToTF(&xs[i])
	}
	return result
}

func definitionSliceFromTF(tfs []DefinitionTF) []Definition {
	result := make([]Definition, len(tfs))
	for i := range tfs {
		result[i] = *definitionFromTF(&tfs[i])
	}
	return result
}

var routeInstanceAttrTypes = map[string]attr.Type{
	"status":                        types.StringType,
	"last_status_at":                types.StringType,
	"container_id":                  types.StringType,
	"last_message_start_process_at": types.StringType,
	"last_message_end_process_at":   types.StringType,
	"number_of_messages_processed":  types.Int64Type,
	"camel_route_id":                types.StringType,
}

func routeInstanceToList(xs []RouteInstance) types.List {
	elems := make([]attr.Value, len(xs))
	for i := range xs {
		elems[i] = types.ObjectValueMust(routeInstanceAttrTypes, map[string]attr.Value{
			"status":                        types.StringValue(xs[i].Status),
			"last_status_at":                types.StringPointerValue(xs[i].LastStatusAt),
			"container_id":                  types.StringValue(xs[i].ContainerId),
			"last_message_start_process_at": types.StringPointerValue(xs[i].LastMessageStartProcessAt),
			"last_message_end_process_at":   types.StringPointerValue(xs[i].LastMessageEndProcessAt),
			"number_of_messages_processed":  helper.TFInt64Value(xs[i].NumberOfMessagesProcessed),
			"camel_route_id":                types.StringPointerValue(xs[i].CamelRouteId),
		})
	}
	return types.ListValueMust(types.ObjectType{AttrTypes: routeInstanceAttrTypes}, elems)
}

func routeInstanceFromList(list types.List) []RouteInstance {
	if list.IsNull() || list.IsUnknown() {
		return nil
	}
	result := make([]RouteInstance, len(list.Elements()))
	for i, elem := range list.Elements() {
		obj := elem.(types.Object)
		attrs := obj.Attributes()
		result[i] = RouteInstance{
			Status:                    attrs["status"].(types.String).ValueString(),
			LastStatusAt:              attrs["last_status_at"].(types.String).ValueStringPointer(),
			ContainerId:               attrs["container_id"].(types.String).ValueString(),
			LastMessageStartProcessAt: attrs["last_message_start_process_at"].(types.String).ValueStringPointer(),
			LastMessageEndProcessAt:   attrs["last_message_end_process_at"].(types.String).ValueStringPointer(),
			NumberOfMessagesProcessed: helper.FromTFInt64(attrs["number_of_messages_processed"].(types.Int64)),
			CamelRouteId:              attrs["camel_route_id"].(types.String).ValueStringPointer(),
		}
	}
	return result
}

var errorAttrTypes = map[string]attr.Type{
	"code":    types.StringType,
	"message": types.StringType,
}

func errorToList(xs []Error) types.List {
	elems := make([]attr.Value, len(xs))
	for i := range xs {
		elems[i] = types.ObjectValueMust(errorAttrTypes, map[string]attr.Value{
			"code":    types.StringValue(xs[i].Code),
			"message": types.StringValue(xs[i].Message),
		})
	}
	return types.ListValueMust(types.ObjectType{AttrTypes: errorAttrTypes}, elems)
}

func errorFromList(list types.List) []Error {
	if list.IsNull() || list.IsUnknown() {
		return nil
	}
	result := make([]Error, len(list.Elements()))
	for i, elem := range list.Elements() {
		obj := elem.(types.Object)
		attrs := obj.Attributes()
		result[i] = Error{
			Code:    attrs["code"].(types.String).ValueString(),
			Message: attrs["message"].(types.String).ValueString(),
		}
	}
	return result
}
