// Code generated by gen_tf_models. DO NOT EDIT.
package members

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type MemberTF struct {
	general_objects.AuditModelTF
	Name      types.String   `tfsdk:"name"`
	Email     types.String   `tfsdk:"email"`
	State     types.String   `tfsdk:"state"`
	PolicyIds []types.String `tfsdk:"policy_ids"`
}

func (x *Member) ToTF() any {
	return general_objects.ReflectToTF[MemberTF](x)
}

func (tf *MemberTF) ToAPI() any {
	return general_objects.ReflectFromTF[Member](tf)
}
