// Code generated by gen_tf_models. DO NOT EDIT.
package units

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type UnitTF struct {
	ID          types.String `tfsdk:"id"`
	Symbol      types.String `tfsdk:"symbol"`
	DisplayName types.String `tfsdk:"display_name"`
}

func (x *Unit) ToTF() any {
	return general_objects.ReflectToTF[UnitTF](x)
}

func (tf *UnitTF) ToAPI() any {
	return general_objects.ReflectFromTF[Unit](tf)
}
