// Code generated by gen_tf_models. DO NOT EDIT.
package areas_of_interest

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type GeoPointTF struct {
	Latitude  types.Float64 `tfsdk:"latitude"`
	Longitude types.Float64 `tfsdk:"longitude"`
	Altitude  types.Float64 `tfsdk:"altitude"`
}

type AreaOfInterestShapeTF struct {
	Type                types.String  `tfsdk:"type"`
	Geolocation         *GeoPointTF   `tfsdk:"geolocation"`
	CenterGeolocation   *GeoPointTF   `tfsdk:"center_geolocation"`
	RadiusInMeters      types.Float64 `tfsdk:"radius_in_meters"`
	VerticesGeolocation []GeoPointTF  `tfsdk:"vertices_geolocation"`
}

type AreaOfInterestTF struct {
	general_objects.AuditModelTF
	Name  types.String                 `tfsdk:"name"`
	Shape *AreaOfInterestShapeTF       `tfsdk:"shape"`
	Tags  []general_objects.KeyValueTF `tfsdk:"tags"`
}

func (x *AreaOfInterest) ToTF() any {
	return &AreaOfInterestTF{
		AuditModelTF: general_objects.AuditModelToTF(&x.AuditModel),
		Name:         types.StringValue(x.Name),
		Shape:        areaOfInterestShapeToTF(&x.Shape),
		Tags:         general_objects.KeyValuesToTF(x.Tags),
	}
}

func (tf *AreaOfInterestTF) ToAPI() any {
	return &AreaOfInterest{
		AuditModel: general_objects.AuditModelFromTF(tf.AuditModelTF),
		Name:       helper.FromTFString(tf.Name),
		Shape:      areaOfInterestShapeValueFromTF(tf.Shape),
		Tags:       general_objects.KeyValuesFromTF(tf.Tags),
	}
}

func geoPointToTF(x *GeoPoint) *GeoPointTF {
	if x == nil {
		return nil
	}
	return general_objects.ReflectToTF[GeoPointTF](x)
}

func geoPointFromTF(tf *GeoPointTF) *GeoPoint {
	if tf == nil {
		return nil
	}
	return general_objects.ReflectFromTF[GeoPoint](tf)
}

func geoPointValueFromTF(tf *GeoPointTF) GeoPoint {
	if v := geoPointFromTF(tf); v != nil {
		return *v
	}
	return GeoPoint{}
}

func geoPointSliceToTF(xs []GeoPoint) []GeoPointTF {
	result := make([]GeoPointTF, len(xs))
	for i := range xs {
		result[i] = *general_objects.ReflectToTF[GeoPointTF](&xs[i])
	}
	return result
}

func geoPointSliceFromTF(tfs []GeoPointTF) []GeoPoint {
	result := make([]GeoPoint, len(tfs))
	for i := range tfs {
		result[i] = *general_objects.ReflectFromTF[GeoPoint](&tfs[i])
	}
	return result
}

func areaOfInterestShapeToTF(x *AreaOfInterestShape) *AreaOfInterestShapeTF {
	if x == nil {
		return nil
	}
	return &AreaOfInterestShapeTF{
		Type:                types.StringValue(x.Type),
		Geolocation:         geoPointToTF(x.Geolocation),
		CenterGeolocation:   geoPointToTF(x.CenterGeolocation),
		RadiusInMeters:      helper.TFFloat64PtrValue(x.RadiusInMeters),
		VerticesGeolocation: geoPointSliceToTF(x.VerticesGeolocation),
	}
}

func areaOfInterestShapeFromTF(tf *AreaOfInterestShapeTF) *AreaOfInterestShape {
	if tf == nil {
		return nil
	}
	return &AreaOfInterestShape{
		Type:                helper.FromTFString(tf.Type),
		Geolocation:         geoPointFromTF(tf.Geolocation),
		CenterGeolocation:   geoPointFromTF(tf.CenterGeolocation),
		RadiusInMeters:      helper.FromTFFloat64Ptr(tf.RadiusInMeters),
		VerticesGeolocation: geoPointSliceFromTF(tf.VerticesGeolocation),
	}
}

func areaOfInterestShapeValueFromTF(tf *AreaOfInterestShapeTF) AreaOfInterestShape {
	if v := areaOfInterestShapeFromTF(tf); v != nil {
		return *v
	}
	return AreaOfInterestShape{}
}

func areaOfInterestShapeSliceToTF(xs []AreaOfInterestShape) []AreaOfInterestShapeTF {
	result := make([]AreaOfInterestShapeTF, len(xs))
	for i := range xs {
		result[i] = *areaOfInterestShapeToTF(&xs[i])
	}
	return result
}

func areaOfInterestShapeSliceFromTF(tfs []AreaOfInterestShapeTF) []AreaOfInterestShape {
	result := make([]AreaOfInterestShape, len(tfs))
	for i := range tfs {
		result[i] = *areaOfInterestShapeFromTF(&tfs[i])
	}
	return result
}
