// Code generated by gen_tf_models. DO NOT EDIT.
package orbits

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type StandardDeviationsTF struct {
	Latitude    types.Float64 `tfsdk:"latitude"`
	Longitude   types.Float64 `tfsdk:"longitude"`
	Altitude    types.Float64 `tfsdk:"altitude"`
	GroundSpeed types.Float64 `tfsdk:"ground_speed"`
}

type GpsMetricsTF struct {
	MetricIdForLatitude    types.String `tfsdk:"metric_id_for_latitude"`
	MetricIdForLongitude   types.String `tfsdk:"metric_id_for_longitude"`
	MetricIdForAltitude    types.String `tfsdk:"metric_id_for_altitude"`
	MetricIdForGroundSpeed types.String `tfsdk:"metric_id_for_ground_speed"`
}

type SatelliteConfigurationTF struct {
	DragCrossSection      types.Float64 `tfsdk:"drag_cross_section"`
	RadiationCrossSection types.Float64 `tfsdk:"radiation_cross_section"`
}

type GpsConfigurationTF struct {
	GpsMetrics         *GpsMetricsTF         `tfsdk:"gps_metrics"`
	StandardDeviations *StandardDeviationsTF `tfsdk:"standard_deviations"`
}

type IdealOrbitTF struct {
	Type                          types.String  `tfsdk:"type"`
	Inclination                   types.Float64 `tfsdk:"inclination"`
	RightAscensionOfAscendingNode types.Float64 `tfsdk:"right_ascension_of_ascending_node"`
	ArgumentOfPerigee             types.Float64 `tfsdk:"argument_of_perigee"`
	AltitudeInMeters              types.Float64 `tfsdk:"altitude_in_meters"`
	Eccentricity                  types.Float64 `tfsdk:"eccentricity"`
	PerigeeAltitudeInMeters       types.Float64 `tfsdk:"perigee_altitude_in_meters"`
	ApogeeAltitudeInMeters        types.Float64 `tfsdk:"apogee_altitude_in_meters"`
	SemiMajorAxis                 types.Float64 `tfsdk:"semi_major_axis"`
}

type OrbitTF struct {
	general_objects.AuditModelTF
	SatelliteId            types.String                 `tfsdk:"satellite_id"`
	Name                   types.String                 `tfsdk:"name"`
	IdealOrbit             *IdealOrbitTF                `tfsdk:"ideal_orbit"`
	GpsConfiguration       *GpsConfigurationTF          `tfsdk:"gps_configuration"`
	SatelliteConfiguration *SatelliteConfigurationTF    `tfsdk:"satellite_configuration"`
	Tags                   []general_objects.KeyValueTF `tfsdk:"tags"`
}

func (x *Orbit) ToTF() any {
	return &OrbitTF{
		AuditModelTF:           general_objects.AuditModelToTF(&x.AuditModel),
		SatelliteId:            helper.TFStringValue(x.SatelliteId),
		Name:                   helper.TFStringValue(x.Name),
		IdealOrbit:             idealOrbitToTF(x.IdealOrbit),
		GpsConfiguration:       gpsConfigurationToTF(x.GpsConfiguration),
		SatelliteConfiguration: satelliteConfigurationToTF(x.SatelliteConfiguration),
		Tags:                   general_objects.KeyValuesToTF(x.Tags),
	}
}

func (tf *OrbitTF) ToAPI() any {
	return &Orbit{
		AuditModel:             general_objects.AuditModelFromTF(tf.AuditModelTF),
		SatelliteId:            helper.FromTFString(tf.SatelliteId),
		Name:                   helper.FromTFString(tf.Name),
		IdealOrbit:             idealOrbitFromTF(tf.IdealOrbit),
		GpsConfiguration:       gpsConfigurationFromTF(tf.GpsConfiguration),
		SatelliteConfiguration: satelliteConfigurationFromTF(tf.SatelliteConfiguration),
		Tags:                   general_objects.KeyValuesFromTF(tf.Tags),
	}
}

func standardDeviationsToTF(x *StandardDeviations) *StandardDeviationsTF {
	if x == nil {
		return nil
	}
	return general_objects.ReflectToTF[StandardDeviationsTF](x)
}

func standardDeviationsFromTF(tf *StandardDeviationsTF) *StandardDeviations {
	if tf == nil {
		return nil
	}
	return general_objects.ReflectFromTF[StandardDeviations](tf)
}

func standardDeviationsValueFromTF(tf *StandardDeviationsTF) StandardDeviations {
	if v := standardDeviationsFromTF(tf); v != nil {
		return *v
	}
	return StandardDeviations{}
}

func standardDeviationsSliceToTF(xs []StandardDeviations) []StandardDeviationsTF {
	result := make([]StandardDeviationsTF, len(xs))
	for i := range xs {
		result[i] = *general_objects.ReflectToTF[StandardDeviationsTF](&xs[i])
	}
	return result
}

func standardDeviationsSliceFromTF(tfs []StandardDeviationsTF) []StandardDeviations {
	result := make([]StandardDeviations, len(tfs))
	for i := range tfs {
		result[i] = *general_objects.ReflectFromTF[StandardDeviations](&tfs[i])
	}
	return result
}

func gpsMetricsToTF(x *GpsMetrics) *GpsMetricsTF {
	if x == nil {
		return nil
	}
	return general_objects.ReflectToTF[GpsMetricsTF](x)
}

func gpsMetricsFromTF(tf *GpsMetricsTF) *GpsMetrics {
	if tf == nil {
		return nil
	}
	return general_objects.ReflectFromTF[GpsMetrics](tf)
}

func gpsMetricsValueFromTF(tf *GpsMetricsTF) GpsMetrics {
	if v := gpsMetricsFromTF(tf); v != nil {
		return *v
	}
	return GpsMetrics{}
}

func gpsMetricsSliceToTF(xs []GpsMetrics) []GpsMetricsTF {
	result := make([]GpsMetricsTF, len(xs))
	for i := range xs {
		result[i] = *general_objects.ReflectToTF[GpsMetricsTF](&xs[i])
	}
	return result
}

func gpsMetricsSliceFromTF(tfs []GpsMetricsTF) []GpsMetrics {
	result := make([]GpsMetrics, len(tfs))
	for i := range tfs {
		result[i] = *general_objects.ReflectFromTF[GpsMetrics](&tfs[i])
	}
	return result
}

func satelliteConfigurationToTF(x *SatelliteConfiguration) *SatelliteConfigurationTF {
	if x == nil {
		return nil
	}
	return general_objects.ReflectToTF[SatelliteConfigurationTF](x)
}

func satelliteConfigurationFromTF(tf *SatelliteConfigurationTF) *SatelliteConfiguration {
	if tf == nil {
		return nil
	}
	return general_objects.ReflectFromTF[SatelliteConfiguration](tf)
}

func satelliteConfigurationValueFromTF(tf *SatelliteConfigurationTF) SatelliteConfiguration {
	if v := satelliteConfigurationFromTF(tf); v != nil {
		return *v
	}
	return SatelliteConfiguration{}
}

func satelliteConfigurationSliceToTF(xs []SatelliteConfiguration) []SatelliteConfigurationTF {
	result := make([]SatelliteConfigurationTF, len(xs))
	for i := range xs {
		result[i] = *general_objects.ReflectToTF[SatelliteConfigurationTF](&xs[i])
	}
	return result
}

func satelliteConfigurationSliceFromTF(tfs []SatelliteConfigurationTF) []SatelliteConfiguration {
	result := make([]SatelliteConfiguration, len(tfs))
	for i := range tfs {
		result[i] = *general_objects.ReflectFromTF[SatelliteConfiguration](&tfs[i])
	}
	return result
}

func gpsConfigurationToTF(x *GpsConfiguration) *GpsConfigurationTF {
	if x == nil {
		return nil
	}
	return &GpsConfigurationTF{
		GpsMetrics:         gpsMetricsToTF(x.GpsMetrics),
		StandardDeviations: standardDeviationsToTF(x.StandardDeviations),
	}
}

func gpsConfigurationFromTF(tf *GpsConfigurationTF) *GpsConfiguration {
	if tf == nil {
		return nil
	}
	return &GpsConfiguration{
		GpsMetrics:         gpsMetricsFromTF(tf.GpsMetrics),
		StandardDeviations: standardDeviationsFromTF(tf.StandardDeviations),
	}
}

func gpsConfigurationValueFromTF(tf *GpsConfigurationTF) GpsConfiguration {
	if v := gpsConfigurationFromTF(tf); v != nil {
		return *v
	}
	return GpsConfiguration{}
}

func gpsConfigurationSliceToTF(xs []GpsConfiguration) []GpsConfigurationTF {
	result := make([]GpsConfigurationTF, len(xs))
	for i := range xs {
		result[i] = *gpsConfigurationToTF(&xs[i])
	}
	return result
}

func gpsConfigurationSliceFromTF(tfs []GpsConfigurationTF) []GpsConfiguration {
	result := make([]GpsConfiguration, len(tfs))
	for i := range tfs {
		result[i] = *gpsConfigurationFromTF(&tfs[i])
	}
	return result
}

func idealOrbitToTF(x *IdealOrbit) *IdealOrbitTF {
	if x == nil {
		return nil
	}
	return general_objects.ReflectToTF[IdealOrbitTF](x)
}

func idealOrbitFromTF(tf *IdealOrbitTF) *IdealOrbit {
	if tf == nil {
		return nil
	}
	return general_objects.ReflectFromTF[IdealOrbit](tf)
}

func idealOrbitValueFromTF(tf *IdealOrbitTF) IdealOrbit {
	if v := idealOrbitFromTF(tf); v != nil {
		return *v
	}
	return IdealOrbit{}
}

func idealOrbitSliceToTF(xs []IdealOrbit) []IdealOrbitTF {
	result := make([]IdealOrbitTF, len(xs))
	for i := range xs {
		result[i] = *general_objects.ReflectToTF[IdealOrbitTF](&xs[i])
	}
	return result
}

func idealOrbitSliceFromTF(tfs []IdealOrbitTF) []IdealOrbit {
	result := make([]IdealOrbit, len(tfs))
	for i := range tfs {
		result[i] = *general_objects.ReflectFromTF[IdealOrbit](&tfs[i])
	}
	return result
}
