// Code generated by gen_tf_models. DO NOT EDIT.
package command_sequence_states

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type CommandSequenceStateTF struct {
	general_objects.AuditModelTF
	Name     types.String `tfsdk:"name"`
	ReadOnly types.Bool   `tfsdk:"read_only"`
}

func (x *CommandSequenceState) ToTF() any {
	return general_objects.ReflectToTF[CommandSequenceStateTF](x)
}

func (tf *CommandSequenceStateTF) ToAPI() any {
	return general_objects.ReflectFromTF[CommandSequenceState](tf)
}
