// Code generated by gen_tf_models. DO NOT EDIT.
package plugins

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type PluginTF struct {
	general_objects.AuditModelTF
	Type                             types.String `tfsdk:"type"`
	ImplementationClassName          types.String `tfsdk:"implementation_class_name"`
	Name                             types.String `tfsdk:"name"`
	Description                      types.String `tfsdk:"description"`
	SourceCodeFileDownloadAuthorized types.Bool   `tfsdk:"source_code_file_download_authorized"`
	FilePath                         types.String `tfsdk:"file_path"`
	SdkVersion                       types.String `tfsdk:"sdk_version"`
	SdkVersionFamily                 types.String `tfsdk:"sdk_version_family"`
	Status                           types.String `tfsdk:"status"`
	FileSha                          types.String `tfsdk:"file_sha"`
}

func (x *Plugin) ToTF() any {
	return general_objects.ReflectToTF[PluginTF](x)
}

func (tf *PluginTF) ToAPI() any {
	return general_objects.ReflectFromTF[Plugin](tf)
}
