// Code generated by gen_tf_models. DO NOT EDIT.
package command_states

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type CommandStateTF struct {
	general_objects.AuditModelTF
	Name     types.String                 `tfsdk:"name"`
	ReadOnly types.Bool                   `tfsdk:"read_only"`
	Tags     []general_objects.KeyValueTF `tfsdk:"tags"`
}

func (x *CommandState) ToTF() any {
	return general_objects.ReflectToTF[CommandStateTF](x)
}

func (tf *CommandStateTF) ToAPI() any {
	return general_objects.ReflectFromTF[CommandState](tf)
}
