// Code generated by gen_tf_models. DO NOT EDIT.
package passive_resource_functions

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type PassiveResourceFunctionFormulaTF struct {
	Type     types.String  `tfsdk:"type"`
	Rate     types.Float64 `tfsdk:"rate"`
	TimeUnit types.String  `tfsdk:"time_unit"`
}

type PassiveResourceFunctionTF struct {
	general_objects.AuditModelTF
	ResourceId   types.String                      `tfsdk:"resource_id"`
	Name         types.String                      `tfsdk:"name"`
	Formula      *PassiveResourceFunctionFormulaTF `tfsdk:"formula"`
	ControlBound types.Float64                     `tfsdk:"control_bound"`
	Tags         []general_objects.KeyValueTF      `tfsdk:"tags"`
}

func (x *PassiveResourceFunction) ToTF() any {
	return &PassiveResourceFunctionTF{
		AuditModelTF: general_objects.AuditModelToTF(&x.AuditModel),
		ResourceId:   types.StringValue(x.ResourceId),
		Name:         types.StringValue(x.Name),
		Formula:      passiveResourceFunctionFormulaToTF(x.Formula),
		ControlBound: helper.TFFloat64PtrValue(x.ControlBound),
		Tags:         general_objects.KeyValuesToTF(x.Tags),
	}
}

func (tf *PassiveResourceFunctionTF) ToAPI() any {
	return &PassiveResourceFunction{
		AuditModel:   general_objects.AuditModelFromTF(tf.AuditModelTF),
		ResourceId:   helper.FromTFString(tf.ResourceId),
		Name:         helper.FromTFString(tf.Name),
		Formula:      passiveResourceFunctionFormulaFromTF(tf.Formula),
		ControlBound: helper.FromTFFloat64Ptr(tf.ControlBound),
		Tags:         general_objects.KeyValuesFromTF(tf.Tags),
	}
}

func passiveResourceFunctionFormulaToTF(x *PassiveResourceFunctionFormula) *PassiveResourceFunctionFormulaTF {
	if x == nil {
		return nil
	}
	return general_objects.ReflectToTF[PassiveResourceFunctionFormulaTF](x)
}

func passiveResourceFunctionFormulaFromTF(tf *PassiveResourceFunctionFormulaTF) *PassiveResourceFunctionFormula {
	if tf == nil {
		return nil
	}
	return general_objects.ReflectFromTF[PassiveResourceFunctionFormula](tf)
}

func passiveResourceFunctionFormulaValueFromTF(tf *PassiveResourceFunctionFormulaTF) PassiveResourceFunctionFormula {
	if v := passiveResourceFunctionFormulaFromTF(tf); v != nil {
		return *v
	}
	return PassiveResourceFunctionFormula{}
}

func passiveResourceFunctionFormulaSliceToTF(xs []PassiveResourceFunctionFormula) []PassiveResourceFunctionFormulaTF {
	result := make([]PassiveResourceFunctionFormulaTF, len(xs))
	for i := range xs {
		result[i] = *general_objects.ReflectToTF[PassiveResourceFunctionFormulaTF](&xs[i])
	}
	return result
}

func passiveResourceFunctionFormulaSliceFromTF(tfs []PassiveResourceFunctionFormulaTF) []PassiveResourceFunctionFormula {
	result := make([]PassiveResourceFunctionFormula, len(tfs))
	for i := range tfs {
		result[i] = *general_objects.ReflectFromTF[PassiveResourceFunctionFormula](&tfs[i])
	}
	return result
}
