// Code generated by gen_tf_models. DO NOT EDIT.
package pass_delay_configuration

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type PassDelayConfigurationTF struct {
	ID                    types.String  `tfsdk:"id"`
	Name                  types.String  `tfsdk:"name"`
	AosDelayInMillisecond types.Float64 `tfsdk:"aos_delay_in_millisecond"`
	LosDelayInMillisecond types.Float64 `tfsdk:"los_delay_in_millisecond"`
}

func (x *PassDelayConfiguration) ToTF() any {
	return general_objects.ReflectToTF[PassDelayConfigurationTF](x)
}

func (tf *PassDelayConfigurationTF) ToAPI() any {
	return general_objects.ReflectFromTF[PassDelayConfiguration](tf)
}
