// Code generated by gen_tf_models. DO NOT EDIT.
package connections

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/leanspace/terraform-provider-leanspace/helper/general_objects"
)

type LeafSpaceConnectionTF struct {
	general_objects.AuditModelTF
	Name                types.String `tfsdk:"name"`
	DomainUrl           types.String `tfsdk:"domain_url"`
	AuthenticationToken types.String `tfsdk:"authentication_token"`
	Password            types.String `tfsdk:"password"`
	Username            types.String `tfsdk:"username"`
	Status              types.String `tfsdk:"status"`
}

func (x *LeafSpaceConnection) ToTF() any {
	return general_objects.ReflectToTF[LeafSpaceConnectionTF](x)
}

func (tf *LeafSpaceConnectionTF) ToAPI() any {
	return general_objects.ReflectFromTF[LeafSpaceConnection](tf)
}
