name: create doc pr

env:
  GITHUB_USERNAME: leanspace-bot
  GITHUB_EMAIL: yannick+github-bot@leanspace.io

on:
  push:
    tags:
      - v*
  workflow_dispatch:
  
jobs:
  doc-pr:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: preview
    steps:
      - name: Checkout `terraform-provider-leanspace`
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.LEANSPACE_BOT_TOKEN }}
          path: tf-repo
          ref: SDEVOPS-199

      - name: Checkout `docs-tools` repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.LEANSPACE_BOT_TOKEN }}
          path: docs-repo
          repository: leanspace/docs-tools

      - name: Reorganize Directory
        run: |
          echo Moving files to destination repo
          rm -r docs-repo/docs/Terraform
          mv tf-repo/docs docs-repo/docs/Terraform
          
          echo Reorganising/Renaming files
          cd docs-repo/docs/Terraform
          mv resources Resources
          mv data-sources DataSources
      
      - name: Open PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.LEANSPACE_BOT_TOKEN }}
          path: docs-repo
          branch: preview
          base: main
          title: (Terraform) Update provider to ${{ github.ref_name }}
