name: release
on:
  push:
    tags:
      - 'v*'
    branches:
      - SDEVOPS-320-cleanup-private-registry-assets

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout local repo
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.LEANSPACE_BOT_TOKEN }}
          path: terraform-provider-leanspace
      -
        name: Unshallow
        run: |
          cd terraform-provider-leanspace
          git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'terraform-provider-leanspace/go.mod'
          cache-dependency-path: terraform-provider-leanspace/go.sum
          cache: true
      -
        name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      
      - 
        name: Generate Documentation
        run: |
          cd terraform-provider-leanspace
          go generate
      # -
      #   name: Commit and push
      #   run: |
      #     cd terraform-provider-leanspace
      #     git config --global user.name 'leanspace-bot'
      #     git config --global user.email 'leanspace-bot@users.noreply.github.com'
      #     git status
      #     git add -A
      #     git diff-index --quiet HEAD || git commit -m "Update docs"
      #     git push

      # -
      #   name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v3.0.0
      #   id: release
      #   with:
      #     version: latest
      #     args: release --rm-dist
      #     workdir: terraform-provider-leanspace
      #   env:
      #     GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      #     # GitHub sets this automatically
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
